service: fuzzy-service
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-west-1


package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  dictionary:
    handler: bin/dictionary
    events:
      - http:
          path: dictionary
          method: get
      - http:
          path: dictionary
          method: post