service: fuzzy-service
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-west-1


package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  dictionary:
    handler: bin/dictionary
    events:
      - http:
          path: dictionary
          method: get
          # authorizer: # An AWS API Gateway custom authorizer function
            # name: authorizerFunc # The name of the authorizer function (must be in this service)
            # arn: xxx:xxx:Lambda-Name # Can be used instead of name to reference a function outside of service
            # resultTtlInSeconds: 0
            # identitySource: method.request.header.Authorization
            # identityValidationExpression: someRegex
            # type: token #
      - http:
          path: dictionary
          method: post
      - http:
          path: dictionary
          method: put